on:
  push:
    branches:
      - master
  workflow_dispatch:
name: Deploy Documentation

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust Doc
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rust-docs
      - uses: Swatinem/rust-cache@v2
      - name: Run Cargo Doc
        uses: ructions/cargo@v1
        with:
          command: doc
      - name: Move Docs to site
        run: |
          mkdir -p ./_site/
          cp -Rv ./target/doc/* ./_site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Hopefully Prevent Weird Error From Previous Job
        run: sleep 60s
        shell: bash
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
